name: Test Prject

on: 
  pull_request: 
    branches: 
      - master

jobs:
  test: 
  runs-on :  ubuntu-latest
  container: 
    image: node:20
  steps:
    - uses: actions/checkout@v2
      with: 
        node-version: 20
      - run: npm ci
      - run: mpn test
      - run: npm  build